<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.profilecondition/xml/schema/CRM/Profilecondition/Profilecondition.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:ae9dfc4e59f2b492ddd6ec3538650325)
 */
use CRM_Profilecondition_ExtensionUtil as E;

/**
 * Database access object for the Profilecondition entity.
 */
class CRM_Profilecondition_DAO_Profilecondition extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_profile_condition';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Profilecondition ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Type of entity (contribution_page, event)
   *
   * @var string
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_type;

  /**
   * ID of the entity
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_id;

  /**
   * Profile ID if specific to a profile
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $profile_id;

  /**
   * Field name in the profile
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $field_name;

  /**
   * Type of condition (default_value, visibility, readonly, conditional)
   *
   * @var string
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $condition_type;

  /**
   * Value for the condition (JSON for complex conditions)
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $condition_value;

  /**
   * Target field for conditional logic
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $target_field;

  /**
   * Value that triggers the condition
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $trigger_value;

  /**
   * Action to take (show, hide, enable, disable)
   *
   * @var string
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $action;

  /**
   * Is this condition active?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Ordering weight
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $weight;

  /**
   * When was the record created.
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $modified_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_profile_condition';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Profileconditions') : E::ts('Profilecondition');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Profilecondition ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_profile_condition.id',
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'entity_type' => [
          'name' => 'entity_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Type'),
          'description' => E::ts('Type of entity (contribution_page, event)'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.entity_type',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Profilecondition_BAO_ProfileCondition::getEntityTypes',
          ],
          'add' => '5.63',
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Entity ID'),
          'description' => E::ts('ID of the entity'),
          'required' => TRUE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.entity_id',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Entity ID"),
          ],
          'add' => '5.63',
        ],
        'profile_id' => [
          'name' => 'profile_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Profile ID'),
          'description' => E::ts('Profile ID if specific to a profile'),
          'required' => FALSE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.profile_id',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_UFGroup',
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Entity ID"),
          ],
          'add' => '5.63',
        ],
        'field_name' => [
          'name' => 'field_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Field Name'),
          'description' => E::ts('Field name in the profile'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.field_name',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'condition_type' => [
          'name' => 'condition_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Condition Type'),
          'description' => E::ts('Type of condition (default_value, visibility, readonly, conditional)'),
          'required' => TRUE,
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.condition_type',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Profilecondition_BAO_ProfileCondition::getConditionTypes',
          ],
          'add' => '5.63',
        ],
        'condition_value' => [
          'name' => 'condition_value',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Condition Value'),
          'description' => E::ts('Value for the condition (JSON for complex conditions)'),
          'required' => FALSE,
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.condition_value',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '5.63',
        ],
        'target_field' => [
          'name' => 'target_field',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Target Field'),
          'description' => E::ts('Target field for conditional logic'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.target_field',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'trigger_value' => [
          'name' => 'trigger_value',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Trigger Value'),
          'description' => E::ts('Value that triggers the condition'),
          'required' => FALSE,
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.trigger_value',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '5.63',
        ],
        'action' => [
          'name' => 'action',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Action'),
          'description' => E::ts('Action to take (show, hide, enable, disable)'),
          'required' => FALSE,
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.action',
          'export' => TRUE,
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Profilecondition_BAO_ProfileCondition::getConditionActions',
          ],
          'add' => '5.63',
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Active'),
          'description' => E::ts('Is this condition active?'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_profile_condition.is_active',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'weight' => [
          'name' => 'weight',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Weight'),
          'description' => E::ts('Ordering weight'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_profile_condition.weight',
          'default' => '0',
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.75',
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'description' => E::ts('When was the record created.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.created_date',
          'headerPattern' => '/created(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Created Date"),
          ],
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Modified Date'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_profile_condition.modified_date',
          'headerPattern' => '/modified(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_profile_condition',
          'entity' => 'Profilecondition',
          'bao' => 'CRM_Profilecondition_DAO_Profilecondition',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'profile_condition', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'profile_condition', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_entity' => [
        'name' => 'index_entity',
        'field' => [
          0 => 'entity_type',
          1 => 'entity_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_profile_condition::0::entity_type::entity_id',
      ],
      'index_field' => [
        'name' => 'index_field',
        'field' => [
          0 => 'field_name',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_profile_condition::0::field_name',
      ],
      'index_active' => [
        'name' => 'index_active',
        'field' => [
          0 => 'is_active',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_profile_condition::0::is_active',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
