-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from file:drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_profile_condition`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_profile_condition
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_profile_condition` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Profilecondition ID',
  `entity_type` varchar(64) NOT NULL COMMENT 'Type of entity (contribution_page, event)',
  `entity_id` int unsigned NOT NULL COMMENT 'ID of the entity',
  `profile_id` int unsigned NULL COMMENT 'Profile ID if specific to a profile',
  `field_name` varchar(255) NOT NULL COMMENT 'Field name in the profile',
  `condition_type` varchar(32) NOT NULL COMMENT 'Type of condition (default_value, visibility, readonly, conditional)',
  `condition_value` text NULL COMMENT 'Value for the condition (JSON for complex conditions)',
  `target_field` varchar(255) NULL COMMENT 'Target field for conditional logic',
  `trigger_value` text NULL COMMENT 'Value that triggers the condition',
  `action` varchar(32) NULL COMMENT 'Action to take (show, hide, enable, disable)',
  `is_active` tinyint NULL DEFAULT 0 COMMENT 'Is this condition active?',
  `weight` int unsigned NULL DEFAULT 0 COMMENT 'Ordering weight',
  `created_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When was the record created.',
  `modified_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `index_entity`(entity_type, entity_id),
  INDEX `index_field`(field_name),
  INDEX `index_active`(is_active),
  CONSTRAINT FK_civicrm_profile_condition_profile_id FOREIGN KEY (`profile_id`) REFERENCES `civicrm_uf_group`(`id`) ON DELETE CASCADE)
ENGINE=InnoDB;
